### PR TITLE
(fix): Set php-fpm to depends on rabbitmq

### PR DESCRIPTION
**Pull request by gem2578**
Fix for https://github.com/Minds/minds/issues/100

### CODE REVIEW

**Comment by polfejs** [comment]
Hello Guys

Who can help me install minds and how much. I have crea8 social script and want to move to minds script.

**Comment by gem2578** [comment]
@polfejs Have you look at this https://github.com/Minds/minds#development-installation

**Comment by gem2578** [comment]
@polfejs it would be better if you opened an issues instead of adding a comment to a random pull request

**Comment by polfejs** [comment]
Will do. Thank you

**Pull request closed without merging**
