### PR TITLE
Fixing spelling mistake in README

### PR DESCRIPTION
**Pull request by fadelardi**
Nothing fancy. Just fixing a small spelling mistake.

### CODE REVIEW

**Comment by ottman** [comment]
Thanks! Can you message me on Minds.com/ottman?

**Comment by strk** [comment]
Does it really take a real-time chat to merge a typo fix ?
As 20 days have gone already, I'm wondering about the health of the Minds development community.

**Comment by strk** [comment]
Funny, got here to find if another issue was reported for the README and this PR is still not filed. I guess it is not worth to report the other issue ? Is it @ottman ?

**Comment by markharding** [comment]
Thanks! We will merge when we have finalized our contributor agreement.

**Comment by markharding** [comment]
@fadelardi Please can you sign https://docs.google.com/document/d/1bFZ1nQhOkvNKxD2ApHKigsFScy3GGQhMYY_batZl8rw/edit?usp=sharing ?

**Comment by fadelardi** [comment]
I'm sorry, what...? 

Three months ago I fixed a small typo in a README file. I was asked to sign up for minds.com, which really wasn't necessary, and I disliked associating my professional life github profile to an online identity in a social platform, but I still went ahead with it. Now I get a link to a gdoc file asking for all my personal information which I'm not really sure why you should have, or what you intend to do with it. All this for fixing a word in a file that no one really seems concerned about. I'm sorry, but no.

How about I close this PR and you guys fix it yourselves, it's pretty simple:

prodution -> production

**Comment by strk** [comment]
Frank, or we can fork it and apply also mine (2 words): #46

These guys are being too serious ...

**Pull request closed without merging**
