### PR TITLE
Added more spam domains

### PR DESCRIPTION
**Pull request by carverh**

### CODE REVIEW

**Comment by markharding** [comment]
Thanks for the request. This list looks a little too long and we might want to consider a different data model here.

**Comment by carverh** [comment]
Like a text document

**Comment by DaSourcerer** [comment]
If I may, I have been toying with the idea of pulling in [Spamhaus' Domain Blacklist](https://www.spamhaus.org/dbl/) for that very purpose. The number of false positives is [stunningly low](https://www.intra2net.com/en/support/antispam/blacklist.php_dnsbl=URIBL_SPAMHAUS_DBL.html). This may indeed work faster than a file lookup, provided a caching DNS server is integrated into the infrastructure. Thoughts?

**Comment by markharding** [comment]
Thanks guys. I'm going to close this pull request, but I think we should open an issue to work out a good spam blacklist solution (perhaps using a cassandra table)

**Pull request closed without merging**
